# Configurate your own model
# countries : ["AL","DE","HU","MK","SE","AT","DK","IE","MT","SI","BA","EE","IT","NL","SK","BE","ES","LT","NO","TR","BG","FI","LU","PL","UA","CH","FR","LV","PT","UK","CY","GR","MD","RO","XK","CZ","HR","ME","RS"]
model :
    type :  brownfield # greenfied
    start : "2018-01-01T00:00:00"
    end   : "2019-01-01T00:00:00"
    operations_resolution : "1h"
    planning_resolution : "365D"
    planning_years: 
      "2030": "2030-01-01T00:00:00"
      "2040": "2041-01-01T00:00:00"
      "2050": "2050-01-01T00:00:00"
    years_represented: 1
timeline:
  historical_alt : 
    CY_1995 :
      start : "1995-01-01T00:00:00"
      end : "1995-12-31T23:00:00"
    CY_2008 :
      start : "2008-01-01T00:00:00"
      end : "2008-12-31T23:00:00"
    CY_2009 :
      start : "2009-01-01T00:00:00"
      end : "2009-12-31T23:00:00"
clustering :
  activate : True
  number_clusters : 12
  number_periods : 24
global_constraints:
  co2_budget:
    "2030": 2200000000
    "2040": 550000000
    "2050": 0.0
  co2_annual_sequestration: 200000000
  renewable_target:
    "2030": 42.5
    "2040": 42.5
    "2050": 42.5  

# Define Europe as country, then, the remaining countries are modeled following requirements
countries : 
  ES : 
    onshore:  "PECD1"
    offshore: "OFF2"
  FR :
    onshore:  "PECD1"
    offshore: "OFF2"

# Sectors optimized
commodity: 
  elec: 
    status: True
  CH4: 
    status: False
  H2: 
    status: False
  CO2: 
    status: False
  bio: 
    status: True
  HC: 
    status: False
  NH3: 
    status: False
  MeOH: 
    status: False
  fossil-CH4: 
    status: False
  fossil-HC: 
    status: False
  global-H2: 
    status: False
  crude: 
    status: False
  coal: 
    status: False
  U-92: 
    status: False
  waste: 
    status: False

transmission: 
  elec: 
    status: True
  CH4: 
    status: True
  H2: 
    status: True
  CO2: 
    status: False

storage:
  large-battery :
    status: True
    investment_method : "no_limits"
  CH4-geo-formation : 
    status: True 
    investment_method : "not_allowed"
  H2-tank : 
    status: False 
    investment_method : "no_limits"
  salt-cavern :
    status: True 
    investment_method : "cumulative_limits"
  CO2-geo-formation :
    status: False 
    investment_method : "cumulative_limits"
  liquids-bunker : 
    status: False 
    investment_method : "no_limits"
  LT-hot-water-tank:
    status: False 
    investment_method : "no_limits"
  heat-storage:
    status: False
    investment_method : "no_limits"


# Technologies definition
technology:
  oil-eng: 
    rename : "oil-eng"
    status: False
    investment_method: "no_limits"
    renewable : False
  oil-eng-existing: 
    rename : "oil-eng-existing"
    status: True
    investment_method: "not_allowed"
    renewable : False
  SCPC:
    rename : "SCPC"
    status: False
    investment_method: "not_allowed"
    renewable : False
  SCPC-existing:
    rename : "SCPC-existing"
    status: True
    investment_method: "not_allowed"
    renewable : False
  SCPC+CC:
    rename : "SCPC+CC"
    status: False
    investment_method: "no_limits"
    renewable : False
  OCGT:
    rename : "OCGT"
    status: False
    investment_method: "no_limits"
    renewable : False
  OCGT+CC:
    rename : "OCGT+CC"
    status: False
    investment_method: "no_limits"
    renewable : False
  CCGT:
    rename : "CCGT"
    status: False
    investment_method: "no_limits"
    renewable : False
  CCGT-existing:
    rename : "CCGT-existing"
    status: True
    investment_method: "not_allowed"
    renewable : False
  CCGT+CC:
    rename : "CCGT+CC"
    status: True
    investment_method: "no_limits"
    renewable : False
  OCGT-H2:
    rename : "OCGT-H2"
    status: False
    investment_method: "no_limits"
    renewable : False
  CCGT-H2:
    rename : "CCGT-H2"
    status: False
    investment_method: "no_limits"
    renewable : False
  wasteST:
    rename : "wasteST"
    status: False
    investment_method: "not_allowed"
    renewable : False
  wasteST-existing:
    rename : "wasteST-existing"
    status: True
    investment_method: "not_allowed"
    renewable : False
  bioST:
    rename : "bioST"
    status: True
    investment_method: "no_limits"
    renewable : True
  bioST-existing:
    rename : "bioST-existing"
    status: True
    investment_method: "not_allowed"
    renewable : True
  bioST+CC:
    rename : "bioST+CC"
    status: False
    investment_method: "no_limits"
    renewable : True
  geothermal:
    rename : "geothermal"
    status: False
    investment_method: "cumulative_limits"
    renewable : True
  nuclear-3:
    rename : "nuclear-3"
    status: False
    investment_method: "no_limits"
    renewable : False
  nuclear-3-existing:
    rename : "nuclear-3-existing"
    status: True
    investment_method: "not_allowed"
    renewable : False
  nuclear-4:
    rename : "nuclear-4"
    status: False
    investment_method: "no_limits"
    renewable : False
  wind-on-existing:
    rename : "wind-on-existing"
    status: True
    investment_method: "not_allowed"
    renewable : True
  wind-off-existing:
    rename : "wind-off-existing"
    status: True
    investment_method: "not_allowed"
    renewable : True
  wind-on-SP335-HH100:
    rename : "wind-on-SP335-HH100"
    status: False
    investment_method: "no_limits"
    renewable : True
  wind-on-SP335-HH150:
    rename : "wind-on-SP335-HH150"
    status: False
    investment_method: "no_limits"
    renewable : True
  wind-on-SP277-HH100:
    rename : "wind-on-SP277-HH100"
    status: False
    investment_method: "no_limits"
    renewable : True
  wind-on-SP277-HH150: 
    rename : "wind-on-SP277-HH150"
    status: False
    investment_method: "no_limits"
    renewable : True
  wind-on-SP199-HH100:
    rename : "wind-on-future"
    status: True
    investment_method: "no_limits"
    renewable : True
  wind-on-SP199-HH150:
    rename : "wind-on-SP198-HH150"
    status: False
    investment_method: "no_limits"
    renewable : True
  wind-off-FB-SP316-HH155:
    rename : "wind-off-FB-SP316-HH155"
    status: False
    investment_method: "no_limits"
    renewable : True
  wind-off-FB-SP370-HH155:
    rename : "wind-off-future"
    status: True
    investment_method: "no_limits"
    renewable : True
  solar-PV-no-tracking:
    rename : "solar-PV"
    status: True
    investment_method: "no_limits"
    renewable : True
  solar-PV-rooftop:
    rename : "solar-PV-rooftop"
    status: False
    investment_method: "no_limits"
    renewable : True
  solar-PV-tracking:
    rename : "solar-PV-tracking"
    status: False
    investment_method: "no_limits"
    renewable : True
  solar-CSP:
    rename : "solar-CSP"
    status: False
    investment_method: "no_limits"
    renewable : True
  fuelcell:
    rename : "fuelcell"
    status: True
    investment_method: "no_limits"
    renewable : False
  hydro-turbine:
    rename : "hydro-turbine"
    status: True
    investment_method: "not_allowed"
    renewable : True
  # biomass production
  biomass-gen:
    status : True
  # gas production
  SMR: 
    status: True
    investment_method: "no_limits"
  SMR+CC:
    status: True
    investment_method: "no_limits"
  PEM: 
    status: True
    investment_method: "no_limits"
  AEC: 
    status: False
    investment_method: "no_limits"
  SOEC: 
    status: False
    investment_method: "no_limits"
  gas-pyrolysis: 
    status: True
    investment_method: "no_limits"
  methanation: 
    status: True
    investment_method: "no_limits"
  bio-diges-up: 
    status: True
    investment_method: "no_limits"
  bio-diges-up+CC: 
    status: False
    investment_method: "no_limits"
  bio-diges-metha: 
    status: True
    investment_method: "no_limits"
  bio-gasif-metha: 
    status: True
    investment_method: "no_limits"
  bio-gasif-metha+CC: 
    status: False
    investment_method: "no_limits"
  DAC: 
    status: True
    investment_method: "no_limits"
  LNG-terminal:
    status: True
    investment_method: "not_allowed"
  gas-extraction: 
    status: True
    investment_method: "not_allowed"
  CH4-import-DZ: 
    status: True
    investment_method: "not_allowed"
  CH4-import-LY: 
    status: True
    investment_method: "not_allowed"
  CH4-import-DZ: 
    status: True
    investment_method: "not_allowed"
  CH4-import-MA: 
    status: True
    investment_method: "not_allowed"
  CH4-import-BL: 
    status: True
    investment_method: "not_allowed"
  CH4-import-RU: 
    status: True
    investment_method: "not_allowed"
  H2-import-DZ: 
    status: True
    investment_method: "not_allowed"
  LH2-terminal: 
    status: True
    investment_method: "not_allowed"
  gas-CHP:
    status: False
    investment_method: "not_allowed"
  coal-CHP:
    status: False
    investment_method: "not_allowed"
  bio-boiler:
    status: True
    investment_method: "no_limits"
  gas-CHP+CC:
    status: False
    investment_method: "not_allowed"
  oil-boiler:
    status: True
    investment_method: "no_limits"
  bio-boiler-DH:
    status: False
    investment_method: "not_allowed"
  fuelcell-CHP:
    status: False
    investment_method: "not_allowed"
  gas-boiler-DH:
    status: False
    investment_method: "not_allowed"
  heatpump-DH:
    status: False
    investment_method: "not_allowed"
  elec-boiler:
    status: True
    investment_method: "no_limits"
  coal-CHP+CC:
    status: False
    investment_method: "not_allowed"
  electric-heating:
    status: True
    investment_method: "no_limits"
  solar-DH:
    status: False
    investment_method: "not_allowed"
  air-heatpump-cool:
    status: True
    investment_method: "no_limits"
  air-heatpump:
    status: True
    investment_method: "no_limits"
  solar-heating:
    status: False
    investment_method: "not_allowed"
  ground-heatpump: 
    status: True
    investment_method: "no_limits"
  gas-boiler:
    status: True
    investment_method: "no_limits"
  waste-CHP:
    status: False
    investment_method: "not_allowed"
  bio-boiler-DH+CC:
    status: False
    investment_method: "not_allowed"
  geothermal-DH:
    status: False
    investment_method: "not_allowed"
  bio-CHP:
    status: False
    investment_method: "not_allowed"
  bio-CHP+CC:
    status: False
    investment_method: "not_allowed"
  waste-DH:
    status: False
    investment_method: "not_allowed"

end-use:
  nonres-cool:
    status: True
  res-cool:
    status: True
  nonres-space:
    status: True
  res-space:
    status: True
  nonres-DHW:
    status: True
  res-DHW:
    status: True
  DH-space:
    status: False
  DH-DHW:
    status: False
    
vehicle:
  car:
    status: True
  car-diesel:
    status: True
  car-gasoline:
    status: True
  car-DR:
    status: True
  car-H2:
    status: True
  car-CNG:
    status: True
  car-LNG:
    status: True
  car-LPG:
    status: True
  van:
    status: True
  van-diesel:
    status: True
  van-gasoline:
    status: True
  van-DR:
    status: True
  van-H2:
    status: True
  van-CNG:
    status: True
  van-LNG:
    status: True
  van-LPG:
    status: True
  truck:
    status: True
  truck-diesel:
    status: True
  truck-gasoline:
    status: True
  truck-DR:
    status: True
  truck-H2:
    status: True
  truck-CNG:
    status: True
  truck-LNG:
    status: True
  truck-LPG:
    status: True
  bus:
    status: True
  bus-diesel:
    status: True
  bus-gasoline:
    status: True
  bus-DR:
    status: True
  bus-H2:
    status: True
  bus-CNG:
    status: True
  bus-LNG:
    status: True
  bus-LPG:
    status: True
  # industrial routes
  ((BM)MeOH)O_ES:
    status: false
  ((BM+H2)MeOH)O_ES:
    status: false
  ((COEL)MeOH)O-MEA_ES:
    status: false
  (BM)FT_ES:
    status: true
  (BM)MeOH_ES:
    status: false
  (BM)NH3_ES:
    status: false
  (COEL)FT-MEA_ES:
    status: false
  (COEL)MeOH-MEA_ES:
    status: false
  (EL)-CC_gco_ES:
    status: false
  (EL)-CC_gfi_ES:
    status: false
  (EL)-CC_gfl_ES:
    status: false
  (EL)PEA_ES:
    status: false
  (EL)PE_ES:
    status: false
  (EL)_gco_ES:
    status: false
  (EL)_gfl_ES:
    status: false
  (H2)-CC_gco_ES:
    status: false
  (H2)-CC_gfi_ES:
    status: false
  (H2)-CC_gfl_ES:
    status: false
  (H2)DRI-EAF_ES:
    status: false
  (H2)FT-DC_ES:
    status: true
  (H2)MeOH-DC_ES:
    status: true
  (H2)NH3_ES:
    status: false
  (H2)PEA_ES:
    status: false
  (H2)PE_ES:
    status: false
  (H2)_gco_ES:
    status: false
  (H2)_gfi_ES:
    status: false
  (H2)_gfl_ES:
    status: false
  (LN)O-MEA_ES:
    status: false
  (LN)O_ES:
    status: false
  (LN+EL)O_ES:
    status: false
  (MeOH)O-MEA_ES:
    status: true
  (NG)-CC_gco_ES:
    status: false
  (NG)-CC_gfi_ES:
    status: false
  (NG)-CC_gfl_ES:
    status: false
  (NG)DRI-EAF-MEA_ES:
    status: false
  (NG)DRI-EAF_ES:
    status: false
  (NG)NH3-DEA_ES:
    status: false
  (NG)NH3-MEA-DEA_ES:
    status: false
  (NG)NH3-MVR-DEA_ES:
    status: false
  (NG)NH3-MVR-MEA-DEA_ES:
    status: false
  (NG)NH3_ES:
    status: true
  (NG)PE-MEA_ES:
    status: false
  (NG)PEA-MEA_ES:
    status: false
  (NG)PEA_ES:
    status: true
  (NG)PE_ES:
    status: true
  (NG)_gco_ES:
    status: true
  (NG)_gfi_ES:
    status: true
  (NG)_gfl_ES:
    status: true
  BF-BOF-MEA_ES:
    status: false
  BF-BOF_ES:
    status: true
  CEM2-(Afm)CaL_ES:
    status: false
  CEM2-(Afm)MEA_ES:
    status: false
  CEM2-(Afm)Oxy-CaL_ES:
    status: false
  CEM2-(Afm)_ES:
    status: false
  CEM2-(BMW)CaL_ES:
    status: false
  CEM2-(BMW)MEA_ES:
    status: false
  CEM2-(BMW)Oxy-CaL_ES:
    status: false
  CEM2-(BMW)Oxy-MEA_ES:
    status: true
  CEM2-(BMW)_ES:
    status: false
  CEM2-(Coal)CaL_ES:
    status: false
  CEM2-(Coal)Oxy-CaL_ES:
    status: false
  CEM2-(Coal)_ES:
    status: false
  DAC_ES:
    status: false
  EU-mix-2018_ES:
    status: false
  LC3-(Afm)CaL_ES:
    status: false
  LC3-(Afm)MEA_ES:
    status: false
  LC3-(Afm)Oxy-CaL_ES:
    status: false
  LC3-(Afm)Oxy-MEA_ES:
    status: false
  LC3-(BMW)Oxy-CaL_ES:
    status: false
  LC3-(BMW)Oxy-MEA_ES:
    status: false
  LC3-(Coal)CaL_ES:
    status: false
  LC3-(NG)CaL_ES:
    status: false
  LC3-(NG)MEA_ES:
    status: false
  LC3-(NG)Oxy-CaL_ES:
    status: false
  MOE_ES:
    status: false
  REF(H2)_ES:
    status: false
  REF-SMR-MEA_ES:
    status: false
  REF-SMR_ES:
    status: true
  Scraps_EAF_ES:
    status: true
  WPI-BOF-MEA_ES:
    status: false

